# Development Environment A Record Configurations
# Add your A record definitions here

dev_web_server:
  fqdn: "web01.dev.internal.company.com"
  ip_addr: "10.1.0.10"
  view: "default"
  ttl: 3600
  comment: "Development web server"
  ea_tags:
    Server_Type: "web"
    Environment: "dev"
    Owner: "DevOps Team"

dev_db_server:
  fqdn: "db01.dev.internal.company.com"
  ip_addr: "10.1.0.20"
  view: "default"
  ttl: 3600
  comment: "Development database server"
  ea_tags:
    Server_Type: "database"
    Environment: "dev"
    Owner: "Database Team"

dev_api_server:
  fqdn: "api.dev-app.company.com"
  ip_addr: "10.1.1.10"
  view: "default"
  ttl: 1800
  comment: "Development API server"
  ea_tags:
    Server_Type: "api"
    Environment: "dev"
    Owner: "Application Team"
