# Development Environment CNAME Record Configurations
# Add your CNAME record definitions here

dev_app_alias:
  alias: "app.dev.internal.company.com"
  canonical: "web01.dev.internal.company.com"
  view: "default"
  ttl: 3600
  comment: "Development application alias"
  ea_tags:
    Record_Type: "alias"
    Environment: "dev"
    Owner: "DevOps Team"

dev_www_alias:
  alias: "www.dev-app.company.com"
  canonical: "api.dev-app.company.com"
  view: "default"
  ttl: 1800
  comment: "Development www alias"
  ea_tags:
    Record_Type: "www_alias"
    Environment: "dev"
    Owner: "Application Team"

dev_admin_alias:
  alias: "admin.dev.internal.company.com"
  canonical: "web01.dev.internal.company.com"
  view: "default"
  ttl: 3600
  comment: "Development admin interface alias"
  ea_tags:
    Record_Type: "admin_alias"
    Environment: "dev"
    Owner: "DevOps Team"
