# Development Environment DNS Zone Configurations
# Add your DNS zone definitions here

dev_internal_zone:
  zone: "dev.internal.company.com"
  view: "default"
  comment: "Development internal zone"
  ea_tags:
    Environment: "dev"
    Type: "internal"
    Owner: "DevOps Team"

dev_app_zone:
  zone: "dev-app.company.com"
  view: "default"
  comment: "Development application zone"
  ea_tags:
    Environment: "dev"
    Type: "application"
    Owner: "Application Team"

dev_test_zone:
  zone: "test.dev.company.com"
  view: "default"
  comment: "Development testing zone"
  ea_tags:
    Environment: "dev"
    Type: "testing"
    Owner: "QA Team"
